language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
sudo: required
install:
  - sudo apt-get install oracle-java8-installer
  - npm install
script:
  - npm test test/tests.js
  - npm test test/testBD.js
  # Borramos la BD para que se regenere en el arranque del servidor
  - rm $TRAVIS_BUILD_DIR/db/database.db && npm start